#!/bin/bash
# Set the variables
AWS_DEFAULT_REGION=us-west-2
BUCKET_NAME=chorme-chris-2021

# Get AWS account ID
ID=$(aws sts get-caller-identity | jq -r '.["Account"]')

# Create the S3 bucket
aws s3api create-bucket \
    --acl public-read \
    --region ${AWS_DEFAULT_REGION} \
    --create-bucket-configuration LocationConstraint=${AWS_DEFAULT_REGION} \
    --bucket ${BUCKET_NAME} 

# Login into ECR
aws ecr get-login-password | docker login --username AWS --password-stdin ${ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

# Create the repository
aws ecr create-repository \
    --repository-name chrome \
    --image-scanning-configuration scanOnPush=true \
    --region ${AWS_DEFAULT_REGION}

# Build the docker image
docker build -t chrome .

# Tag the image
docker tag chrome:latest ${ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/chrome:latest

# Push to ECR
docker push ${ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/chrome:latest

# Prepare Lambda functon role
aws iam create-role --role-name lambda-ex --assume-role-policy-document file://trust-policy.json
aws iam attach-role-policy --role-name lambda-ex --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
aws iam attach-role-policy --role-name lambda-ex --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess

# Create Lambda function
aws lambda create-function \
	--function-name chrome \
	--memory-size=2048 \
	--timeout=180 \
	--code ImageUri="${ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/chrome:latest" \
	--role arn:aws:iam::${ID}:role/lambda-ex \
	--package-type Image